In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt





import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Indian Cities AQI.csv')
df.head()

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status,unit,note
0,30-04-2025,Maharashtra,Amravati,2,PM10,78,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
1,30-04-2025,Bihar,Purnia,1,CO,56,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
2,30-04-2025,Madhya Pradesh,Katni,1,O3,98,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
3,30-04-2025,Chhattisgarh,Tumidih,1,PM10,103,Moderate,number_of_monitoring_stations in Absolute Numb...,NaN
4,30-04-2025,Assam,Byrnihat,1,PM2.5,61,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN

In [3]:
# # removing the useless feature

df.drop(columns=['note', 'unit'], inplace=True)
df

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status
0,30-04-2025,Maharashtra,Amravati,2,PM10,78,Satisfactory
1,30-04-2025,Bihar,Purnia,1,CO,56,Satisfactory
2,30-04-2025,Madhya Pradesh,Katni,1,O3,98,Satisfactory
3,30-04-2025,Chhattisgarh,Tumidih,1,PM10,103,Moderate
4,30-04-2025,Assam,Byrnihat,1,PM2.5,61,Satisfactory
...,...,...,...,...,...,...,...
235780,01-04-2022,Bihar,Arrah,1,PM10,210,Poor
235781,01-04-2022,Rajasthan,Jaipur,3,"PM2.5,PM10",158,Moderate
235782,01-04-2022,Maharashtra,Chandrapur,2,PM2.5,201,Poor
235783,01-04-2022,Uttar Pradesh,Varanasi,4,PM10,128,Moderate
235784,01-04-2022,Odisha,Brajrajnagar,1,O3,270,Poor

In [ ]:
df['date'] = pd.to_datetime(df['date'])

print(df['date'].nunique())     # checking for unique values

df['date'].info()

1125
<class 'pandas.core.series.Series'>
RangeIndex: 235785 entries, 0 to 235784
Series name: date
Non-Null Count   Dtype
--------------   -----
235785 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.8 MB

In [10]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

a = pd.DataFrame(mlb.fit_transform(df['prominent_pollutants']), columns=mlb.classes_)

a

        ,  .  0  1  2  3  5  C  H  M  N  O  P  S
0       0  0  1  1  0  0  0  0  0  1  0  0  1  0
1       0  0  0  0  0  0  0  1  0  0  0  1  0  0
2       0  0  0  0  0  1  0  0  0  0  0  1  0  0
3       0  0  1  1  0  0  0  0  0  1  0  0  1  0
4       0  1  0  0  1  0  1  0  0  1  0  0  1  0
...    .. .. .. .. .. .. .. .. .. .. .. .. .. ..
235780  0  0  1  1  0  0  0  0  0  1  0  0  1  0
235781  1  1  1  1  1  0  1  0  0  1  0  0  1  0
235782  0  1  0  0  1  0  1  0  0  1  0  0  1  0
235783  0  0  1  1  0  0  0  0  0  1  0  0  1  0
235784  0  0  0  0  0  1  0  0  0  0  0  1  0  0

[235785 rows x 14 columns]