In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
df =  pd.read_csv("Categorical.csv")
df

             name   Longitude   Latitude      continent
0           Aruba  -69.982677  12.520880  North America
1     Afghanistan   66.004734  33.835231           Asia
2          Angola   17.537368 -12.293361         Africa
3        Anguilla  -63.064989  18.223959  North America
4         Albania   20.049834  41.142450         Europe
..            ...         ...        ...            ...
236         Samoa -172.164851 -13.753243        Oceania
237         Yemen   47.586762  15.909280           Asia
238  South Africa   25.083901 -29.000341         Africa
239        Zambia   27.774759 -13.458242         Africa
240      Zimbabwe   29.851441 -19.004204         Africa

[241 rows x 4 columns]

In [3]:
print(df['continent'].nunique())
print(df['continent'].unique().tolist())

8
['North America', 'Asia', 'Africa', 'Europe', 'South America', 'Oceania', 'Antarctica', 'Seven seas (open ocean)']

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.head()

          name  Longitude   Latitude      continent
0        Aruba -69.982677  12.520880  North America
1  Afghanistan  66.004734  33.835231           Asia
2       Angola  17.537368 -12.293361         Africa
3     Anguilla -63.064989  18.223959  North America
4      Albania  20.049834  41.142450         Europe

In [6]:
df[(df['continent'] == 'Africa') & (df['name']=='Angola')]

     name  Longitude   Latitude continent
2  Angola  17.537368 -12.293361    Africa

In [7]:
condition = (df['continent'] == 'Asia')

np.round(df.loc[condition, ['Longitude', 'Latitude']], 2)

     Longitude  Latitude
1        66.00     33.84
7        54.30     23.91
9        44.93     40.29
17       47.55     40.29
22       90.24     23.87
24       50.54     26.04
35      114.72      4.52
36       90.40     27.41
41      103.82     36.56
54       33.57     35.26
55       33.01     34.92
77       43.51     42.17
90      114.11     22.40
96      117.24     -2.22
98       79.61     22.89
99      104.85    -10.65
102      54.27     32.58
103      43.74     33.04
105      35.00     31.46
109      36.77     31.25
110     138.03     37.59
111      77.18     35.39
112      67.29     48.16
114      74.54     41.46
115     104.91     12.72
118     127.84     36.39
120      47.59     29.33
121     103.74     18.50
122      35.88     33.92
127      80.70      7.61
132     113.51     22.22
144      96.49     21.19
146     103.05     46.83
153     109.70      3.79
163      83.92     28.25
166      56.09     20.61
167      69.34     29.95
171     122.88     11.78
176     127.19     40.15
179      35.20     31.92
181      51.18     25.31
186      44.54     24.12
190     103.82      1.36
209      38.51     35.03
213     101.00     15.12
214      71.01     38.53
215      59.37     39.12
216     125.84     -8.83
220      35.17     39.06
221     120.95     23.75
227      63.14     41.76
233     106.30     16.65
237      47.59     15.91

In [8]:
condition = (df['Latitude'] >= 30) & (df['Longitude'] >= 30)

df.loc[condition, ['Longitude', 'Latitude']]

      Longitude   Latitude
1     66.004734  33.835231
9     44.929933  40.289526
17    47.545999  40.288272
41   103.819074  36.561765
54    33.568481  35.262775
55    33.006002  34.916672
77    43.507803  42.168558
102   54.274070  32.575033
103   43.743531  33.039706
105   35.004447  31.461101
109   36.771361  31.245791
110  138.030896  37.592301
111   77.180119  35.392363
112   67.291494  48.156881
114   74.541655  41.462219
118  127.839161  36.385240
122   35.880161  33.923066
146  103.052998  46.826815
176  127.192480  40.153503
179   35.196287  31.916139
183   96.686561  61.980522
209   38.507882  35.025474
214   71.013626  38.530454
215   59.371000  39.115541
220   35.168953  39.061603
224   31.383265  48.996567
227   63.140015  41.755542

In [9]:
df.loc[:, ['Longitude', 'Latitude']].sum()

Longitude    3425.906569
Latitude     4137.819814
dtype: float64

In [10]:
df['continent'] == 'Asia'

0      False
1       True
2      False
3      False
4      False
       ...
236    False
237     True
238    False
239    False
240    False
Name: continent, Length: 241, dtype: bool

In [11]:
df[df['continent'] == 'Asia']

                     name   Longitude   Latitude continent
1             Afghanistan   66.004734  33.835231      Asia
7    United Arab Emirates   54.300167  23.905282      Asia
9                 Armenia   44.929933  40.289526      Asia
17             Azerbaijan   47.545999  40.288272      Asia
22             Bangladesh   90.238127  23.867312      Asia
24                Bahrain   50.541969  26.042051      Asia
35                 Brunei  114.722030   4.519690      Asia
36                 Bhutan   90.401882  27.411066      Asia
41                  China  103.819074  36.561765      Asia
54              N. Cyprus   33.568481  35.262775      Asia
55                 Cyprus   33.006002  34.916672      Asia
77                Georgia   43.507803  42.168558      Asia
90              Hong Kong  114.113805  22.398277      Asia
96              Indonesia  117.240114  -2.215055      Asia
98                  India   79.611976  22.885782      Asia
99      Indian Ocean Ter.  104.851898 -10.647851      Asia
102                  Iran   54.274070  32.575033      Asia
103                  Iraq   43.743531  33.039706      Asia
105                Israel   35.004447  31.461101      Asia
109                Jordan   36.771361  31.245791      Asia
110                 Japan  138.030896  37.592301      Asia
111       Siachen Glacier   77.180119  35.392363      Asia
112            Kazakhstan   67.291494  48.156881      Asia
114            Kyrgyzstan   74.541655  41.462219      Asia
115              Cambodia  104.906943  12.720048      Asia
118                 Korea  127.839161  36.385240      Asia
120                Kuwait   47.587005  29.334313      Asia
121               Lao PDR  103.737724  18.502174      Asia
122               Lebanon   35.880161  33.923066      Asia
127             Sri Lanka   80.701082   7.612665      Asia
132                 Macao  113.509321  22.223117      Asia
144               Myanmar   96.488433  21.185666      Asia
146              Mongolia  103.052998  46.826815      Asia
153              Malaysia  109.697623   3.789868      Asia
163                 Nepal   83.915826  28.248914      Asia
166                  Oman   56.091662  20.605153      Asia
167              Pakistan   69.339579  29.949752      Asia
171           Philippines  122.883933  11.775368      Asia
176       Dem. Rep. Korea  127.192480  40.153503      Asia
179             Palestine   35.196287  31.916139      Asia
181                 Qatar   51.184796  25.306012      Asia
186          Saudi Arabia   44.536863  24.122458      Asia
190             Singapore  103.817256   1.358761      Asia
209                 Syria   38.507882  35.025474      Asia
213              Thailand  101.002881  15.118158      Asia
214            Tajikistan   71.013626  38.530454      Asia
215          Turkmenistan   59.371000  39.115541      Asia
216           Timor-Leste  125.844390  -8.828892      Asia
220                Turkey   35.168953  39.061603      Asia
221                Taiwan  120.954273  23.753993      Asia
227            Uzbekistan   63.140015  41.755542      Asia
233               Vietnam  106.299147  16.646017      Asia
237                 Yemen   47.586762  15.909280      Asia

In [12]:
print(df[df['continent'] == 'Asia']['Longitude'].max())
print(df[df['continent'] == 'Asia']['Latitude'].max())

138.0308956
48.15688067

In [13]:
a = df[df['continent'] == 'Asia']
a_max = a.max()

a[['name', 'Longitude']]

                     name   Longitude
1             Afghanistan   66.004734
7    United Arab Emirates   54.300167
9                 Armenia   44.929933
17             Azerbaijan   47.545999
22             Bangladesh   90.238127
24                Bahrain   50.541969
35                 Brunei  114.722030
36                 Bhutan   90.401882
41                  China  103.819074
54              N. Cyprus   33.568481
55                 Cyprus   33.006002
77                Georgia   43.507803
90              Hong Kong  114.113805
96              Indonesia  117.240114
98                  India   79.611976
99      Indian Ocean Ter.  104.851898
102                  Iran   54.274070
103                  Iraq   43.743531
105                Israel   35.004447
109                Jordan   36.771361
110                 Japan  138.030896
111       Siachen Glacier   77.180119
112            Kazakhstan   67.291494
114            Kyrgyzstan   74.541655
115              Cambodia  104.906943
118                 Korea  127.839161
120                Kuwait   47.587005
121               Lao PDR  103.737724
122               Lebanon   35.880161
127             Sri Lanka   80.701082
132                 Macao  113.509321
144               Myanmar   96.488433
146              Mongolia  103.052998
153              Malaysia  109.697623
163                 Nepal   83.915826
166                  Oman   56.091662
167              Pakistan   69.339579
171           Philippines  122.883933
176       Dem. Rep. Korea  127.192480
179             Palestine   35.196287
181                 Qatar   51.184796
186          Saudi Arabia   44.536863
190             Singapore  103.817256
209                 Syria   38.507882
213              Thailand  101.002881
214            Tajikistan   71.013626
215          Turkmenistan   59.371000
216           Timor-Leste  125.844390
220                Turkey   35.168953
221                Taiwan  120.954273
227            Uzbekistan   63.140015
233               Vietnam  106.299147
237                 Yemen   47.586762

In [14]:
# printing sum of all continents



continent = df['continent'].unique().tolist()
print(continent)

for i in continent:
    data = df[df['continent'] == i]
    print(f"------------------{i}------------------")
    print(data['Longitude'].max())
    print(data['Latitude'].max())

['North America', 'Asia', 'Africa', 'Europe', 'South America', 'Oceania', 'Antarctica', 'Seven seas (open ocean)']
------------------North America------------------
-41.34191127
74.71051289
------------------Asia------------------
138.0308956
48.15688067
------------------Africa------------------
46.70473674
34.11956246
------------------Europe------------------
96.68656112
68.75015572
------------------South America------------------
-53.09783113
7.12422421
------------------Oceania------------------
171.4849235
15.82927563
------------------Antarctica------------------
19.92108951
-80.50857913
------------------Seven seas (open ocean)------------------
73.5205171
3.7287092

In [15]:

def check(df):

    continent = df['continent'].unique().tolist()       # by default unique returns array hence converted into a list

    names = []
    max_longitude = []
    max_latitude = []

    for i in continent:

        # append continent names to 'names'
        if i not in names:
            names.append(i)

        temp = df[df['continent'] == i]

        max_longitude.append(temp['Longitude'].max())
        max_latitude.append(temp['Latitude'].max())

    

    a = pd.DataFrame({
        'names' : names,
        'max_longitude' : max_longitude,
        'max_latitude' : max_latitude
    })

    return a

In [16]:
check(df)

                     names  max_longitude  max_latitude
0            North America     -41.341911     74.710513
1                     Asia     138.030896     48.156881
2                   Africa      46.704737     34.119562
3                   Europe      96.686561     68.750156
4            South America     -53.097831      7.124224
5                  Oceania     171.484924     15.829276
6               Antarctica      19.921090    -80.508579
7  Seven seas (open ocean)      73.520517      3.728709