In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('smoking_health_data_final.csv')
df.head()

   age   sex current_smoker  heart_rate blood_pressure  cigs_per_day   chol
0   54  male            yes          95         110/72           NaN  219.0
1   45  male            yes          64         121/72           NaN  248.0
2   58  male            yes          81       127.5/76           NaN  235.0
3   42  male            yes          90       122.5/80           NaN  225.0
4   42  male            yes          62         119/80           NaN  226.0

#### Applying `pivot_table`

A Pivot Table is simply a tool that takes a massive, unreadable list of raw data and "spins" it into a tiny, clean, highly-readable summary grid.

It answers the question: "How can I cross-reference two different categories to find the average/sum?"

### `pd.pivot_table()` Parameters Cheat Sheet

| Parameter | Required? | What it does | Example / Options |
| :--- | :---: | :--- | :--- |
| **`data`** | Yes | The raw dataframe you want to compress. | `data=df` |
| **`index`** | Yes | The column(s) you want running down the **LEFT** side as Rows. | `index='Store_Location'` |
| **`columns`** | No | The column(s) you want running across the **TOP** as Headers. | `columns='Date'` |
| **`values`** | No | The specific column of numbers you want to do math on *inside* the cells. If left blank, Pandas tries to do math on every numeric column! | `values='Daily_Revenue'` |
| **`aggfunc`** | No | The mathematical rule for how to smash the numbers together. Defaults to `'mean'`. | `'mean'`, `'sum'`, `'count'`, `'max'`, `'min'`, or `['sum', 'mean']` |
| **`fill_value`** | No | What to put in cells where no data exists. Replaces `NaN` with a value of your choice. | `fill_value=0` |
| **`margins`** | No | If `True`, adds a "Grand Total" row at the bottom and a "Grand Total" column at the far right. Defaults to `False`. | `margins=True` |
| **`margins_name`** | No | What to name the Grand Total row/column if `margins=True` is turned on. Defaults to the word `"All"`. | `margins_name='Total'` |
| **`dropna`** | No | If `True`, it deletes any columns/rows where every single cell is completely blank. Defaults to `True` to keep tables clean. | `dropna=True` |



### Basic Usage Example:
If you want to know the **Total Revenue** for each **Store Location**, broken down by **Date**:

**`pd.pivot_table(data=df, index='Store_Location', columns='Date', values='Daily_Revenue', aggfunc='sum')`**

In [4]:
pd.pivot_table(df, index='age', columns='current_smoker', values='cigs_per_day', aggfunc='mean')

current_smoker   no        yes
age
32              NaN  15.000000
33              0.0  10.000000
34              0.0  15.555556
35              0.0  16.608696
36              0.0  18.911111
37              0.0  20.388889
38              0.0  16.728395
39              0.0  19.744444
40              0.0  19.772727
41              0.0  19.292135
42              0.0  19.158416
43              0.0  20.734043
44              0.0  19.172043
45              0.0  16.439560
46              0.0  19.386139
47              0.0  18.717949
48              0.0  19.936709
49              0.0  17.693548
50              0.0  20.557143
51              0.0  17.642857
52              0.0  18.481481
53              0.0  20.884615
54              0.0  20.166667
55              0.0  16.531915
56              0.0  17.803922
57              0.0  16.782609
58              0.0  17.023256
59              0.0  19.743590
60              0.0  15.472222
61              0.0  15.121212
62              0.0  18.068966
63              0.0  19.516129
64              0.0  16.521739
65              0.0  11.636364
66              0.0  13.777778
67              0.0  15.928571
68              0.0  15.000000
69              0.0   9.333333
70              0.0        NaN

In [6]:
print(df.columns)
df.info()

Index(['age', 'sex', 'current_smoker', 'heart_rate', 'blood_pressure',
       'cigs_per_day', 'chol'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             3900 non-null   int64
 1   sex             3900 non-null   object
 2   current_smoker  3900 non-null   object
 3   heart_rate      3900 non-null   int64
 4   blood_pressure  3900 non-null   object
 5   cigs_per_day    3886 non-null   float64
 6   chol            3893 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 213.4+ KB

In [14]:
# what age group of ppl consume more cigrates, and what gender consumes more cigrattes
pd.pivot_table(df, index='age', columns='sex', values='cigs_per_day', aggfunc='mean')

sex     female       male
age
32   15.000000        NaN
33    6.666667   0.000000
34    7.272727  12.000000
35    6.200000  15.176471
36    8.270270  12.674419
37   10.930233  14.674419
38    7.303030  12.652174
39    7.085366  16.611111
40    7.861702  17.950000
41    6.538462  15.881579
42    8.064516  15.800000
43    8.855263  18.228571
44    7.268657  15.069767
45    6.756410  13.458333
46    7.735849  16.985075
47    8.837838  15.500000
48    5.289474  13.964286
49    4.294118  15.480769
50    7.441176  14.136364
51    4.739726  14.338710
52    4.500000  10.014286
53    4.784615  14.090909
54    2.671429  14.735849
55    2.411765  11.916667
56    4.672131  11.754717
57    4.196429   9.421053
58    3.607843  11.183673
59    3.278689  12.954545
60    2.666667   8.254902
61    3.379310   7.046512
62    1.212766  10.152174
63    2.516129  10.951220
64    2.584906   6.942857
65    0.433333   5.476190
66    1.650000   6.500000
67    2.043478  10.352941
68   10.000000   4.166667
69    0.000000   9.333333
70    0.000000        NaN

In [13]:
# what age group of ppl consume more cigrates, and what gender consumes more cigrattes
pd.pivot_table(df, index='age', columns='sex', values='cigs_per_day', aggfunc=['max', 'mean'])

       max             mean
sex female  male     female       male
age
32    15.0   NaN  15.000000        NaN
33    15.0   0.0   6.666667   0.000000
34    20.0  25.0   7.272727  12.000000
35    30.0  40.0   6.200000  15.176471
36    43.0  40.0   8.270270  12.674419
37    43.0  60.0  10.930233  14.674419
38    35.0  50.0   7.303030  12.652174
39    30.0  60.0   7.085366  16.611111
40    43.0  70.0   7.861702  17.950000
41    43.0  43.0   6.538462  15.881579
42    30.0  43.0   8.064516  15.800000
43    30.0  45.0   8.855263  18.228571
44    30.0  43.0   7.268657  15.069767
45    30.0  43.0   6.756410  13.458333
46    43.0  60.0   7.735849  16.985075
47    43.0  50.0   8.837838  15.500000
48    35.0  60.0   5.289474  13.964286
49    30.0  60.0   4.294118  15.480769
50    30.0  60.0   7.441176  14.136364
51    25.0  50.0   4.739726  14.338710
52    30.0  35.0   4.500000  10.014286
53    40.0  50.0   4.784615  14.090909
54    20.0  43.0   2.671429  14.735849
55    35.0  45.0   2.411765  11.916667
56    40.0  60.0   4.672131  11.754717
57    43.0  43.0   4.196429   9.421053
58    30.0  60.0   3.607843  11.183673
59    35.0  60.0   3.278689  12.954545
60    20.0  40.0   2.666667   8.254902
61    30.0  30.0   3.379310   7.046512
62    20.0  43.0   1.212766  10.152174
63    40.0  43.0   2.516129  10.951220
64    30.0  40.0   2.584906   6.942857
65     9.0  25.0   0.433333   5.476190
66    20.0  30.0   1.650000   6.500000
67    20.0  60.0   2.043478  10.352941
68    20.0  15.0  10.000000   4.166667
69     0.0  23.0   0.000000   9.333333
70     0.0   NaN   0.000000        NaN

### learning to replace texts in data frame

In [16]:
df.head()

   age   sex current_smoker  heart_rate blood_pressure  cigs_per_day   chol
0   54  male            yes          95         110/72           NaN  219.0
1   45  male            yes          64         121/72           NaN  248.0
2   58  male            yes          81       127.5/76           NaN  235.0
3   42  male            yes          90       122.5/80           NaN  225.0
4   42  male            yes          62         119/80           NaN  226.0

In [32]:
print(df['sex'].unique())

a = df['sex'].copy()
a = a.str.lower().str.replace('male', 'MARD').str.replace('female', 'AURAT')
a

['male' 'female']

0       MARD
1       MARD
2       MARD
3       MARD
4       MARD
        ...
3895    MARD
3896    MARD
3897    MARD
3898    MARD
3899    MARD
Name: sex, Length: 3900, dtype: object

In [ ]:
print(a.unique())       # the reason you got feMARD bcoz ".str" never reads the text like words, it reads the text like letters
# for eg it will not read it like "male", but rather it will read it like 'm-a-l-e' as separate letters, and if the letters are in same sequence as the same as target word set in ".replace", then it will do the work

['MARD' 'feMARD']

In [39]:
a = df['sex'].copy()

a = a.map({
    'male':'MARD',
    'female':'AURAT'
})

print(a.unique())
a.sample(5)

['MARD' 'AURAT']

1163    AURAT
768      MARD
3710     MARD
1370    AURAT
3671     MARD
Name: sex, dtype: object