# Handling time

In [10]:
import pandas as pd
import numpy as np

In [11]:
time = pd.read_csv('messages.csv')
date = pd.read_csv('orders.csv')

date = date.drop(columns=['product_id', 'city_id', 'orders'])
time = time.drop(columns=['msg'])
time.head()

                  date
0  2013-12-15 00:50:00
1  2014-04-29 23:40:00
2  2012-12-30 00:21:00
3  2014-11-28 00:31:00
4  2013-10-26 23:11:00

### **Working with time**

In [12]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [13]:
# extracting hour, minute, and seconds
time['hour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

time.head(3)

                 date  hour  minute  second
0 2013-12-15 00:50:00     0      50       0
1 2014-04-29 23:40:00    23      40       0
2 2012-12-30 00:21:00     0      21       0

In [14]:
# as both date and time are mentioned together, hence extracting time separately
time['time'] = time['date'].dt.time
time.head(3)

                 date  hour  minute  second      time
0 2013-12-15 00:50:00     0      50       0  00:50:00
1 2014-04-29 23:40:00    23      40       0  23:40:00
2 2012-12-30 00:21:00     0      21       0  00:21:00

In [15]:
# extracting time difference
import datetime         
today = datetime.datetime.today()
today - time['date']

0     4427 days 19:20:44.122884
1     4291 days 20:30:44.122884
2     4777 days 19:49:44.122884
3     4079 days 19:39:44.122884
4     4476 days 20:59:44.122884
                 ...
995   5066 days 19:20:44.122884
996   4387 days 20:56:44.122884
997   4852 days 20:33:44.122884
998   4968 days 20:36:44.122884
999   4240 days 20:45:44.122884
Name: date, Length: 1000, dtype: timedelta64[ns]

In [16]:
# extracting in seconds
(today - time['date']) / np.timedelta64(1, 's')

0      3.825624e+08
1      3.708162e+08
2      4.128042e+08
3      3.524964e+08
4      3.868020e+08
           ...
995    4.377720e+08
996    3.791122e+08
997    4.192868e+08
998    4.293094e+08
999    3.664107e+08
Name: date, Length: 1000, dtype: float64

In [17]:
# extracting minutes
(today - time['date']) / np.timedelta64(1, 'm')

0      6.376041e+06
1      6.180271e+06
2      6.880070e+06
3      5.874940e+06
4      6.446700e+06
           ...
995    7.296201e+06
996    6.318537e+06
997    6.988114e+06
998    7.155157e+06
999    6.106846e+06
Name: date, Length: 1000, dtype: float64

In [18]:
# extracting hours
(today - time['date']) / np.timedelta64(1, 'h')

0      106267.345590
1      103004.512256
2      114667.828923
3       97915.662256
4      107444.995590
           ...
995    121603.345590
996    105308.945590
997    116468.562256
998    119252.612256
999    101780.762256
Name: date, Length: 1000, dtype: float64