In [ ]:
import numpy as np
import pandas as pd

import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings('ignore')

In [2]:
# loading diabetis dataset from github

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']


df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
print(df.info())
print("---------------------------------------------------------------")
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None
---------------------------------------------------------------

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [4]:
# in the above dataset all the missing values are represented by 0, hence it will not show missing values, hence we have to change 0 to 'NaN'

df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:

# Replacing zero values with NaN in columns 
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Imputing missing values with mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [7]:
# making a function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)       # we are asking to suggest the best estimator starting from 50 to 200, based on the past data
    max_depth = trial.suggest_int('max_depth', 3, 20)

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score

In [8]:

# Creating a study object and optimizing the objective function
study = optuna.create_study(
    direction = 'maximize', 
    sampler = optuna.samplers.TPESampler(),
    pruner = optuna.pruners.HyperbandPruner()
)  # aiming to maximize accuracy

study.optimize(objective, n_trials=50)  # Running 50 trials to find the best hyperparameters

[I 2026-03-10 07:11:16,745] A new study created in memory with name: no-name-eef622c7-b481-427a-9ff1-90844eb8808a
[I 2026-03-10 07:11:18,325] Trial 0 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 140, 'max_depth': 4}. Best is trial 0 with value: 0.7579143389199254.
[I 2026-03-10 07:11:19,082] Trial 1 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 72, 'max_depth': 13}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-10 07:11:21,043] Trial 2 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 179, 'max_depth': 16}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:22,360] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 106, 'max_depth': 5}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:23,326] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 15}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:24,596] Trial 5 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 113, 'max_depth': 20}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:26,568] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 179, 'max_depth': 17}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:27,535] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 97, 'max_depth': 11}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:30,871] Trial 8 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 196, 'max_depth': 11}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:31,443] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 64, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:32,035] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 152, 'max_depth': 19}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-10 07:11:32,493] Trial 11 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 125, 'max_depth': 20}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:33,071] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 151, 'max_depth': 17}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:33,573] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 134, 'max_depth': 17}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:34,603] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 169, 'max_depth': 14}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:36,923] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 198, 'max_depth': 20}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:38,804] Trial 16 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 166, 'max_depth': 16}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:40,346] Trial 17 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 119, 'max_depth': 9}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:41,571] Trial 18 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 91, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:42,218] Trial 19 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 54, 'max_depth': 13}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:42,680] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 57, 'max_depth': 9}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:44,777] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 13}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:46,270] Trial 22 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 128, 'max_depth': 15}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:46,654] Trial 23 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 50, 'max_depth': 13}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:47,737] Trial 24 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 87, 'max_depth': 19}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:49,091] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 148, 'max_depth': 15}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:50,784] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 163, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:51,955] Trial 27 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 107, 'max_depth': 9}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:52,893] Trial 28 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 74, 'max_depth': 11}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:54,337] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 16}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:55,557] Trial 30 finished with value: 0.7728119180633146 and parameters: {'n_estimators': 122, 'max_depth': 12}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:56,642] Trial 31 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 102, 'max_depth': 19}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:57,915] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 20}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:11:58,928] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 109, 'max_depth': 20}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:00,084] Trial 34 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 131, 'max_depth': 3}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:01,794] Trial 35 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 113, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:02,671] Trial 36 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 81, 'max_depth': 16}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:03,365] Trial 37 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 69, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:04,738] Trial 38 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 138, 'max_depth': 14}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:06,807] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 186, 'max_depth': 14}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:07,793] Trial 40 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 96, 'max_depth': 17}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:08,428] Trial 41 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 66, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:08,924] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 19}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:09,638] Trial 43 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:10,785] Trial 44 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 77, 'max_depth': 15}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:12,629] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 157, 'max_depth': 16}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:13,357] Trial 46 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 18}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:14,342] Trial 47 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 83, 'max_depth': 19}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:14,916] Trial 48 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 17}. Best is trial 11 with value: 0.7802607076350093.
[I 2026-03-10 07:12:16,829] Trial 49 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 174, 'max_depth': 12}. Best is trial 11 with value: 0.7802607076350093.

### Optuna: Deep Dive into `create_study()`

The `optuna.create_study()` function is the starting point of any Optuna optimization process. It initializes a "Study" object, which is responsible for managing the entire history of trials, tracking the best hyperparameters, and deciding where the algorithm should search next.

Understanding the parameters inside `create_study()` allows you to control exactly how the optimization behaves, from standardizing randomness to saving progress halfway through.

Here is an in-depth look at its parameters.

### 1. `direction` (String)
*   **What it does:** Tells Optuna what your ultimate goal is regarding the evaluation metric you return in your objective function.
*   **Options:**
    *   `'maximize'`: Use this if you are trying to get the highest score possible (for accuracy) (e.g., Accuracy, F1-Score, R-squared).
    *   `'minimize'`: Use this if you are trying to get the lowest score possible (for errors) (e.g., Mean Squared Error, Log Loss).
*   **Default:** `'minimize'`

### 2. `directions` (List of Strings)
*   **What it does:** Used strictly for Multi-Objective Optimization. If your objective function returns *two or more* scores (for example, you want high accuracy BUT ALSO fast prediction time), you pass a list of directions.
*   **Example:** `directions=['maximize', 'minimize']`
*   **Note:** You cannot use `direction` and `directions` at the same time.

### 3. `study_name` (String)
*   **What it does:** Gives your study a custom, readable name instead of a random UUID.
*   **Why it's useful:** If you are saving your studies to a database (using the `storage` parameter), giving it a name is required so you can easily find it and resume it later.

### 4. `storage` (String or Optuna Storage Object)
*   **What it does:** By default, Optuna saves the history of all trials in the computer's RAM. If the script crashes, you lose everything. `storage` allows you to save the progress to a permanent database (like SQLite, PostgreSQL, or MySQL).
*   **Example:** `storage='sqlite:///my_study.db'`
*   **Why it's useful:** It allows you to pause a study and resume it the next day. It also allows multiple computers (distributed computing) to work on the exact same study simultaneously by pointing them to the same database URL.

### 5. `sampler` (Optuna Sampler Object)
*   **What it does:** Defines the exact algorithm Optuna uses to guess the next set of hyperparameters. 
*   **Options:**
    *   `TPESampler()`: The default. Uses the Tree-structured Parzen Estimator (Bayesian Optimization). This is almost always the best choice.
    *   `RandomSampler()`: Blindly picks random combinations (equivalent to RandomSearchCV).
    *   `GridSampler()`: Exhaustively tries combinations from a predefined grid (equivalent to GridSearchCV).
    *   `CmaEsSampler()`: Excellent for continuous mathematical functions but overkill for standard ML algorithms.
*   **Why it's useful:** You can pass arguments into the sampler, such as setting a random seed to make your optimization 100% reproducible: `sampler=optuna.samplers.TPESampler(seed=42)`.

### 6. `pruner` (Optuna Pruner Object)
*   **What it does:** Defines the algorithm used to kill bad, unpromising trials early to save time. 
*   **Options:**
    *   `MedianPruner()`: The default. It kills a trial if its intermediate score is worse than the median score of all previous trials at the same step.
    *   `HyperbandPruner()`: A more aggressive, advanced pruner that allocates resources to the best-performing models very quickly.
*   **Why it's useful:** If you are training a Deep Learning model that takes 50 epochs, the pruner will stop the training at epoch 5 if it predicts the final result will be terrible.

### 7. `load_if_exists` (Boolean)
*   **What it does:** Used in conjunction with `study_name` and `storage`. 
*   **Options:**
    *   `False` (Default): If you try to create a study with a name that already exists in your database, Optuna will throw a `DuplicatedStudyError`.
    *   `True`: Instead of crashing, Optuna will simply load the massive history of the past study and seamlessly continue adding new trials to it.

---

### Example: A fully configured `create_study`

```python
import optuna

study = optuna.create_study(
    direction='maximize',                     # We want high accuracy
    study_name='xgboost_optimization_v1',     # Give it a readable name
    storage='sqlite:///optuna_history.db',    # Save it to a local SQL file so we don't lose progress
    load_if_exists=True,                      # If we run this script again tomorrow, just pick up where we left off
    sampler=optuna.samplers.TPESampler(seed=42) # Make the randomness reproducible
)

# Start the optimization
# study.optimize(objective, n_trials=100)

In [9]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')
study.best_trial

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 125, 'max_depth': 20}

FrozenTrial(number=11, state=<TrialState.COMPLETE: 1>, values=[0.7802607076350093], datetime_start=datetime.datetime(2026, 3, 10, 7, 11, 32, 36862), datetime_complete=datetime.datetime(2026, 3, 10, 7, 11, 32, 493215), params={'n_estimators': 125, 'max_depth': 20}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_estimators': IntDistribution(high=200, log=False, low=50, step=1), 'max_depth': IntDistribution(high=20, log=False, low=3, step=1)}, trial_id=11, value=None)

In [10]:
# Training a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

test_accuracy = accuracy_score(y_test, y_pred)

print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

### Using different Samplers in Optuna

In [11]:
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score

In [ ]:
# using random sampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  
study.optimize(objective, n_trials=50)

[I 2026-03-10 07:17:41,591] A new study created in memory with name: no-name-acd5fed8-c379-4a35-8c29-25f27c453230
[I 2026-03-10 07:17:42,928] Trial 0 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 127, 'max_depth': 7}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:43,560] Trial 1 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 124, 'max_depth': 4}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:44,425] Trial 2 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 195, 'max_depth': 4}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:45,184] Trial 3 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 162, 'max_depth': 19}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:45,632] Trial 4 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 51, 'max_depth': 9}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:45,975] Trial 5 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 69, 'max_depth': 8}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:46,518] Trial 6 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 135, 'max_depth': 6}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:47,203] Trial 7 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 164, 'max_depth': 4}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:47,876] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 142, 'max_depth': 6}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:48,480] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 15}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:48,817] Trial 10 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 81, 'max_depth': 8}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:49,702] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 18}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:50,799] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 167, 'max_depth': 18}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:51,294] Trial 13 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 93, 'max_depth': 4}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:51,646] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 18}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:52,838] Trial 15 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 138, 'max_depth': 4}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:53,334] Trial 16 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 51, 'max_depth': 11}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:53,679] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 78, 'max_depth': 13}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:54,652] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 196, 'max_depth': 14}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:55,072] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 102, 'max_depth': 4}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:55,736] Trial 20 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 146, 'max_depth': 11}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:55,991] Trial 21 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 53, 'max_depth': 6}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:56,405] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 104, 'max_depth': 8}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:56,970] Trial 23 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 126, 'max_depth': 7}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-03-10 07:17:57,569] Trial 24 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 73, 'max_depth': 18}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:17:58,688] Trial 25 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 128, 'max_depth': 9}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:00,062] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 17}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:00,708] Trial 27 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 165, 'max_depth': 6}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:00,912] Trial 28 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 52, 'max_depth': 4}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:01,268] Trial 29 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 85, 'max_depth': 11}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:02,304] Trial 30 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 199, 'max_depth': 16}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:03,221] Trial 31 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 184, 'max_depth': 10}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:04,228] Trial 32 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 52, 'max_depth': 15}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:04,962] Trial 33 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 20}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:05,782] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 155, 'max_depth': 13}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:06,580] Trial 35 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 170, 'max_depth': 5}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:06,854] Trial 36 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 55, 'max_depth': 12}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:07,167] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 68, 'max_depth': 11}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:07,648] Trial 38 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 109, 'max_depth': 15}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:08,110] Trial 39 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 100, 'max_depth': 11}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:08,617] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 103, 'max_depth': 14}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:09,105] Trial 41 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 85, 'max_depth': 10}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:09,861] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 113, 'max_depth': 8}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:10,274] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 82, 'max_depth': 19}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:10,814] Trial 44 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 7}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:12,455] Trial 45 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 141, 'max_depth': 3}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:13,269] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 73, 'max_depth': 9}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:15,335] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 183, 'max_depth': 7}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:15,999] Trial 48 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 8}. Best is trial 24 with value: 0.7839851024208566.
[I 2026-03-10 07:18:17,392] Trial 49 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 104, 'max_depth': 10}. Best is trial 24 with value: 0.7839851024208566.

In [13]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7839851024208566
Best hyperparameters: {'n_estimators': 73, 'max_depth': 18}

In [14]:
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

test_accuracy = accuracy_score(y_test, y_pred)

print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

In [ ]:
# using grid search sampler

search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-03-10 07:19:52,262] A new study created in memory with name: no-name-5fa258fc-9521-45ab-81bf-6819d2a052d0
[I 2026-03-10 07:19:52,720] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-10 07:19:53,326] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-10 07:19:53,644] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:54,057] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:54,463] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:54,676] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:55,327] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:56,107] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:56,766] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:57,580] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:58,372] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:19:59,384] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:20:01,346] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-10 07:20:01,626] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-10 07:20:02,494] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-10 07:20:03,117] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [16]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [17]:
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

test_accuracy = accuracy_score(y_test, y_pred)

print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

### Using different Optuna Visualizations

In [ ]:
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

# optimization history
plot_optimization_history(study).show()
# the graph below shows that, as the number of trials increases the accuracy also increases
# based on the graph you can also tune the model for your next prediction

In [ ]:
# parallel coordinates plot
plot_parallel_coordinate(study).show()
# it shows you the relationship btwn trials, max_depth, and n_estimators

In [ ]:
# Slice Plot
plot_slice(study).show()

In [ ]:
# Contour Plot
plot_contour(study).show()

# the darker blue region is representing the higher accuracy

In [30]:
# Hyperparameter Importance
plot_param_importances(study).show()

### Running Different ML Models

In [31]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [32]:
# here we are using different ML models and also explicitely specifying their hyperparameters

def objective(trial):
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [33]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-03-10 07:52:41,276] A new study created in memory with name: no-name-664b1f78-3e74-49ac-a25e-e3fd927adaf0
[I 2026-03-10 07:52:42,902] Trial 0 finished with value: 0.7802607076350094 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 185, 'learning_rate': 0.04846251669333463, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:43,205] Trial 1 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 67, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:45,732] Trial 2 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 272, 'learning_rate': 0.03926593664165612, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:48,388] Trial 3 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 191, 'learning_rate': 0.07077116090016139, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:49,256] Trial 4 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 241, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:49,304] Trial 5 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 3.1611946204455657, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:49,587] Trial 6 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 72, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:51,393] Trial 7 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 124, 'learning_rate': 0.02419628412555064, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:51,733] Trial 8 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 76, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:56,632] Trial 9 finished with value: 0.7635009310986964 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 196, 'learning_rate': 0.038215930168627385, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:56,806] Trial 10 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 88.57489434977454, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:58,001] Trial 11 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 135, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:52:59,473] Trial 12 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 143, 'learning_rate': 0.2801969953837329, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:53:00,157] Trial 13 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 153, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 0 with value: 0.7802607076350094.
[I 2026-03-10 07:53:00,180] Trial 14 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1065605853254056, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7877094972067038.
[I 2026-03-10 07:53:00,238] Trial 15 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10364509092984182, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7877094972067038.
[I 2026-03-10 07:53:00,276] Trial 16 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16509447748957434, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7877094972067038.
[I 2026-03-10 07:53:00,454] Trial 17 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10985674490711714, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7877094972067038.
[I 2026-03-10 07:53:00,508] Trial 18 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6744723844361092, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7877094972067038.
[I 2026-03-10 07:53:00,546] Trial 19 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 0.6092229561051452, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 14 with value: 0.7877094972067038.
[I 2026-03-10 07:53:00,579] Trial 20 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12740443623618758, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,625] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1010848463348058, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,666] Trial 22 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.40198603001306615, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,699] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2784965047026181, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,754] Trial 24 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.592162964205122, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,787] Trial 25 finished with value: 0.6871508379888268 and parameters: {'classifier': 'SVM', 'C': 37.34387482930973, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,855] Trial 26 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 14.228818459432238, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,907] Trial 27 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.2834795934889342, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,935] Trial 28 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.18999355544971402, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:00,974] Trial 29 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.928059867385669, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:01,008] Trial 30 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1314962564811757, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:01,066] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1029376118766013, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:01,106] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22991650903930633, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:01,143] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10018042181724165, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:01,189] Trial 34 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3782184987613388, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:01,256] Trial 35 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.19908664150016334, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:11,665] Trial 36 finished with value: 0.696461824953445 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 293, 'learning_rate': 0.010282490200709711, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:11,756] Trial 37 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 6.284603373578319, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:11,828] Trial 38 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 0.16252251642320978, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:14,742] Trial 39 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 230, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:17,507] Trial 40 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 110, 'learning_rate': 0.2601966441263888, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:17,558] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16913609157903978, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:17,645] Trial 42 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14960492425664593, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:17,743] Trial 43 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.38660255828788465, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:17,798] Trial 44 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15214644874392846, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:19,450] Trial 45 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 104, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:19,661] Trial 46 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.29238403619697073, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:23,325] Trial 47 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 225, 'learning_rate': 0.11713499993732412, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:23,401] Trial 48 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 1.2860530016799876, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:23,480] Trial 49 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5369023065185041, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:26,449] Trial 50 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 270, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:26,509] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14471210073055732, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:26,562] Trial 52 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15671892530051962, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:26,628] Trial 53 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14848986082976856, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:26,709] Trial 54 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 0.1619558343815521, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:26,798] Trial 55 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.74250773646864, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:26,877] Trial 56 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13845655763971784, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:26,962] Trial 57 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2531342399731071, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,477] Trial 58 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 53, 'learning_rate': 0.011220857328725797, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,535] Trial 59 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22471844954622336, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,586] Trial 60 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12069339966826645, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,654] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14113398014693035, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,717] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13682044883174616, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,767] Trial 63 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3540233905875879, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,825] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.20917474550524592, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,892] Trial 65 finished with value: 0.7765363128491621 and parameters: {'classifier': 'SVM', 'C': 0.13225604674824817, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:28,985] Trial 66 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5185883305145981, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:30,647] Trial 67 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 166, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:30,827] Trial 68 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13267253248269512, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:30,913] Trial 69 finished with value: 0.7243947858472998 and parameters: {'classifier': 'SVM', 'C': 0.272062268841742, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:30,969] Trial 70 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19691993016415685, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:31,029] Trial 71 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10010470742367143, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:31,092] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12982304917037793, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:31,166] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12557509445726794, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:31,796] Trial 74 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 70.72703920466232, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:31,884] Trial 75 finished with value: 0.7616387337057727 and parameters: {'classifier': 'SVM', 'C': 0.18571276554107216, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:31,949] Trial 76 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.30982097926177155, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:34,488] Trial 77 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 94, 'learning_rate': 0.13876629450086186, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:34,563] Trial 78 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.10094274781783305, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:34,623] Trial 79 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21931256032159754, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7895716945996275.
[I 2026-03-10 07:53:34,682] Trial 80 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16115956009322321, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7895716945996275.

In [34]:
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.12740443623618758, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [ ]:
# printing the details of each trial
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.780261,2026-03-10 07:52:41.325450,2026-03-10 07:52:42.901324,0 days 00:00:01.575874,NaN,NaN,GradientBoosting,NaN,NaN,0.048463,3.0,8.0,9.0,185.0,COMPLETE
1,1,0.767225,2026-03-10 07:52:42.905445,2026-03-10 07:52:43.205419,0 days 00:00:00.299974,NaN,False,RandomForest,NaN,NaN,NaN,6.0,4.0,3.0,67.0,COMPLETE
2,2,0.743017,2026-03-10 07:52:43.206673,2026-03-10 07:52:45.732738,0 days 00:00:02.526065,NaN,NaN,GradientBoosting,NaN,NaN,0.039266,7.0,10.0,2.0,272.0,COMPLETE
3,3,0.743017,2026-03-10 07:52:45.733615,2026-03-10 07:52:48.388353,0 days 00:00:02.654738,NaN,NaN,GradientBoosting,NaN,NaN,0.070771,19.0,6.0,7.0,191.0,COMPLETE
4,4,0.759777,2026-03-10 07:52:48.389194,2026-03-10 07:52:49.256643,0 days 00:00:00.867449,NaN,True,RandomForest,NaN,NaN,NaN,10.0,10.0,2.0,241.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.772812,2026-03-10 07:53:39.328770,2026-03-10 07:53:44.245882,0 days 00:00:04.917112,NaN,NaN,GradientBoosting,NaN,NaN,0.021285,10.0,7.0,3.0,211.0,COMPLETE
96,96,0.754190,2026-03-10 07:53:44.247552,2026-03-10 07:53:44.338665,0 days 00:00:00.091113,0.234685,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.785847,2026-03-10 07:53:44.340777,2026-03-10 07:53:44.569256,0 days 00:00:00.228479,21.877090,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.754190,2026-03-10 07:53:44.570631,2026-03-10 07:53:44.653321,0 days 00:00:00.082690,0.450565,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.763501,2026-03-10 07:53:44.657862,2026-03-10 07:53:47.582053,0 days 00:00:02.924191,NaN,False,RandomForest,NaN,NaN,NaN,20.0,2.0,9.0,257.0,COMPLETE

In [ ]:
study.trials_dataframe()['params_classifier'].value_counts()
# shows that out of 100 trails SVM has been run only 76 times, some for others

params_classifier
SVM                 76
GradientBoosting    12
RandomForest        12
Name: count, dtype: int64

In [ ]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()
# printing the average accuracy of every model

params_classifier
GradientBoosting    0.745034
RandomForest        0.764277
SVM                 0.776120
Name: value, dtype: float64

In [39]:
plot_optimization_history(study).show()

In [40]:
plot_slice(study).show()

In [41]:
plot_param_importances(study).show()